version: 1.0.{build}
os: Visual Studio 2015
environment:
  COVERALLS_REPO_TOKEN:
    secure: cvcD92FnkXFKn86BXo5WvferYsX2xUdjNkT2erZ5SG4H6JIHON87CoqN0Kzis2k5
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- ps: nuget restore
build:
  verbosity: normal
artifacts:
- path: opencovertests.xml
  name: opencovertests.xml